# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Feng Wu
title: Research assistant at Purdue University
email: wu1239@purdue[dot]edu
website: https://calmair521.github.io/
# Social links

# Social links

# About Section
# about_title: About Me
about_profile_image: images/Feng.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Feng Wu. I'm currently doing my PhD degree in Civil(Architectural) Engineering and 
  a research assistant studying at Purdue University.I also hold a master degree of computer engineering. 
  Before came Purdue in 2017, I have been working as a full-time control engineer at Delta controls for 
  6 years, which I deal with different HAVC control and
  energy management systems. 
  
  
# Projects Section
# projects_title: Implemented projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  During my spare time, I have a lot of hobbies. First of all, I'm big fan of NBA and Kobe Bryant is my favourite player. 
  I like playing basketball, tennis, golf and other sports. In addition, I like playing guitar, which I think is a good way 
  to have a relax. I'm an easy-going and open minded person. I'm happy to make friends with different people and to offer help.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
